// AUTO-GENERATED by scripts/generate-api-contracts.mjs. Do not edit manually.
// Source: contracts/openapi.json (OpenAPI 3.1.0).

import Foundation

public enum APIProblemPathPart: Codable, Equatable {
    case key(String)
    case index(Int)

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(String.self) {
            self = .key(value)
        } else {
            self = .index(try container.decode(Int.self))
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .key(let value): try container.encode(value)
        case .index(let value): try container.encode(value)
        }
    }
}

public struct APIProblemIssue: Codable, Equatable {
    public let path: [APIProblemPathPart]
    public let code: String
    public let message: String
}

public struct APIProblem: Codable, Equatable, Error {
    public let type: String
    public let title: String
    public let status: Int
    public let detail: String
    public let instance: String
    public let code: String
    public let requestId: String
    public let retryAfter: Int?
    public let errors: [APIProblemIssue]?
}

public struct KernelItem: Codable, Equatable {
    public let id: String
    public let label: String
}

public struct KernelEchoQuery: Codable, Equatable {
    public let cursor: String?
    public let limit: Int?

    public init(cursor: String? = nil, limit: Int? = nil) {
        self.cursor = cursor
        self.limit = limit
    }
}

public struct KernelEchoBody: Codable, Equatable {
    public let message: String

    public init(message: String) {
        self.message = message
    }
}

public struct KernelEchoCursor: Codable, Equatable {
    public let version: Int
    public let offset: Int
}

public struct KernelEchoPagination: Codable, Equatable {
    public let limit: Int
    public let hasMore: Bool
    public let nextCursor: String?
}

public struct KernelEchoMeta: Codable, Equatable {
    public let requestId: String
    public let pagination: KernelEchoPagination
}

public struct KernelEchoGetResponse: Codable, Equatable {
    public let data: [KernelItem]
    public let meta: KernelEchoMeta
}

public struct KernelEchoPostData: Codable, Equatable {
    public let echo: String
}

public struct KernelEchoPostMeta: Codable, Equatable {
    public let requestId: String
}

public struct KernelEchoPostResponse: Codable, Equatable {
    public let data: KernelEchoPostData
    public let meta: KernelEchoPostMeta
}

public struct ShellBootstrapUser: Codable, Equatable {
    public let id: String
    public let name: String
    public let email: String?
    public let role: String
    public let roleLabel: String
    public let avatarUrl: String?
    public let initials: String
}

public struct ShellBootstrapPreferences: Codable, Equatable {
    public let theme: String
    public let themeId: String
    public let catppuccinAccent: String
    public let accentColor: String
    public let backgroundColor: String
    public let cardColor: String
    public let foregroundColor: String
    public let secondaryTextColor: String
    public let surfaceColor: String
    public let borderColor: String
}

public struct ShellBootstrapBrand: Codable, Equatable {
    public let logoLight: String?
    public let logoDark: String?
}

public struct ShellBootstrapCounters: Codable, Equatable {
    public let pendingTasks: Int
    public let unreadNotifications: Int
}

public struct ShellBootstrapNotification: Codable, Equatable {
    public let id: String
    public let message: String
    public let createdAt: String
    public let authorName: String?
    public let avatarUrl: String?
    public let read: Bool
}

public struct ShellBootstrapData: Codable, Equatable {
    public let user: ShellBootstrapUser
    public let capabilities: [String]
    public let preferences: ShellBootstrapPreferences
    public let brand: ShellBootstrapBrand
    public let counters: ShellBootstrapCounters
    public let notifications: [ShellBootstrapNotification]
}

public struct ShellBootstrapMeta: Codable, Equatable {
    public let requestId: String
}

public struct ShellBootstrapResponse: Codable, Equatable {
    public let data: ShellBootstrapData
    public let meta: ShellBootstrapMeta
}

public enum AppRouteMode: String, Codable, Equatable {
    case native
    case web
}

public struct AppRouteRule: Codable, Equatable {
    public let path: String
    public let mode: AppRouteMode
}

public struct AppConfigData: Codable, Equatable {
    public let version: Int
    public let defaultMode: AppRouteMode
    public let routes: [AppRouteRule]
}

public struct AppConfigMeta: Codable, Equatable {
    public let requestId: String
}

public struct AppConfigResponse: Codable, Equatable {
    public let data: AppConfigData
    public let meta: AppConfigMeta
}

public enum APIJSONValue: Codable, Equatable {
    case string(String)
    case number(Double)
    case boolean(Bool)
    case object([String: APIJSONValue])
    case array([APIJSONValue])
    case null

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if container.decodeNil() { self = .null }
        else if let value = try? container.decode(Bool.self) { self = .boolean(value) }
        else if let value = try? container.decode(Double.self) { self = .number(value) }
        else if let value = try? container.decode(String.self) { self = .string(value) }
        else if let value = try? container.decode([String: APIJSONValue].self) { self = .object(value) }
        else { self = .array(try container.decode([APIJSONValue].self)) }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .string(let value): try container.encode(value)
        case .number(let value): try container.encode(value)
        case .boolean(let value): try container.encode(value)
        case .object(let value): try container.encode(value)
        case .array(let value): try container.encode(value)
        case .null: try container.encodeNil()
        }
    }
}

public struct SyncMutation: Codable, Equatable {
    public let mutationId: String
    public let clientId: String
    public let entityType: String
    public let entityId: String
    public let operation: String
    public let baseVersion: Int?
    public let data: [String: APIJSONValue]?
}

public struct SyncPushBody: Codable, Equatable {
    public let mutations: [SyncMutation]
}

public struct SyncChange: Codable, Equatable {
    public let sequence: String
    public let entityType: String
    public let entityId: String
    public let operation: String
    public let version: Int
    public let data: [String: APIJSONValue]?
    public let deletedAt: String?
    public let changedAt: String
}

public struct SyncPullQuery: Codable, Equatable {
    public let cursor: String?
    public let limit: Int?
    public init(cursor: String? = nil, limit: Int? = nil) {
        self.cursor = cursor
        self.limit = limit
    }
}

public struct SyncPullData: Codable, Equatable {
    public let changes: [SyncChange]
    public let hasMore: Bool
    public let nextCursor: String?
    public let retentionDays: Int
}

public struct SyncPullResponse: Codable, Equatable {
    public let data: SyncPullData
    public let meta: SyncResponseMeta
}

public struct SyncMutationResult: Codable, Equatable {
    public let mutationId: String
    public let duplicate: Bool
    public let entityType: String
    public let entityId: String
    public let operation: String
    public let version: Int
    public let deleted: Bool
    public let data: [String: APIJSONValue]?
    public let changedAt: String
}

public struct SyncPushData: Codable, Equatable {
    public let results: [SyncMutationResult]
}

public struct SyncPushResponse: Codable, Equatable {
    public let data: SyncPushData
    public let meta: SyncResponseMeta
}

public struct SyncBootstrapData: Codable, Equatable {
    public let entities: [SyncChange]
    public let latestCursor: String?
    public let retentionDays: Int
}

public struct SyncResponseMeta: Codable, Equatable {
    public let requestId: String
}

public struct SyncBootstrapResponse: Codable, Equatable {
    public let data: SyncBootstrapData
    public let meta: SyncResponseMeta
}

public struct DashboardUser: Codable, Equatable {
    public let id: String
    public let name: String
    public let role: String
    public let specialty: String?
}

public struct DashboardSummary: Codable, Equatable {
    public let activeClients: Int
    public let assignedTasks: Int
    public let overdueEditingTasks: Int
    public let overduePublicationTasks: Int
    public let publishedThisMonth: Int
    public let pendingApprovals: Int
    public let scheduledToday: Int
    public let priorityTasks: Int
    public let totalIncome: Double?
    public let totalReceivable: Double?
}

public struct DashboardTaskClient: Codable, Equatable {
    public let id: String
    public let name: String
    public let logoUrl: String?
}

public struct DashboardAssignee: Codable, Equatable {
    public let id: String
    public let name: String
    public let imageUrl: String?
}

public struct DashboardTask: Codable, Equatable {
    public let id: String
    public let title: String
    public let type: String
    public let status: String
    public let priority: String
    public let dueDate: String?
    public let scheduledAt: String?
    public let updatedAt: String
    public let client: DashboardTaskClient
    public let assignedTo: DashboardAssignee?
}

public struct DashboardPipelineStage: Codable, Equatable {
    public let key: String
    public let label: String
    public let count: Int
}

public struct DashboardApproval: Codable, Equatable {
    public let id: String
    public let title: String
    public let kind: String
    public let clientId: String
    public let clientName: String
    public let clientLogoUrl: String?
    public let updatedAt: String
}

public struct DashboardWorkload: Codable, Equatable {
    public let userId: String
    public let userName: String
    public let userRole: String
    public let userSpecialty: String?
    public let userImageUrl: String?
    public let pendingTasksCount: Int
    public let weeklyCapacity: Int
    public let utilizationPct: Double
}

public struct DashboardTransaction: Codable, Equatable {
    public let id: String
    public let description: String
    public let type: String
    public let amount: Double
    public let date: String
}

public struct DashboardData: Codable, Equatable {
    public let generatedAt: String
    public let user: DashboardUser
    public let summary: DashboardSummary
    public let pipeline: [DashboardPipelineStage]
    public let agenda: [DashboardTask]
    public let priorityTasks: [DashboardTask]
    public let approvals: [DashboardApproval]
    public let workloads: [DashboardWorkload]
    public let recentTransactions: [DashboardTransaction]
}

public struct DashboardResponse: Codable, Equatable {
    public let data: DashboardData
    public let meta: SyncResponseMeta
}

public enum TotemAPIError: Error {
    case invalidURL
    case http(status: Int, problem: APIProblem?)
    case decoding(Error)
}

public final class TotemAPIClient {
    private let baseURL: URL
    private let session: URLSession
    private let csrfToken: String?
    private let additionalHeaders: [String: String]

    public init(
        baseURL: URL,
        session: URLSession = .shared,
        csrfToken: String? = nil,
        additionalHeaders: [String: String] = [:]
    ) {
        self.baseURL = baseURL
        self.session = session
        self.csrfToken = csrfToken
        self.additionalHeaders = additionalHeaders
    }

    public func kernelEchoList(query: KernelEchoQuery = KernelEchoQuery()) async throws -> KernelEchoGetResponse {
        var components = URLComponents(url: baseURL.appendingPathComponent("api/v1/_kernel/echo"), resolvingAgainstBaseURL: false)
        var items: [URLQueryItem] = []
        if let cursor = query.cursor { items.append(URLQueryItem(name: "cursor", value: cursor)) }
        if let limit = query.limit { items.append(URLQueryItem(name: "limit", value: String(limit))) }
        components?.queryItems = items.isEmpty ? nil : items
        guard let url = components?.url else { throw TotemAPIError.invalidURL }
        return try await request(url: url, method: "GET", body: nil, as: KernelEchoGetResponse.self)
    }

    public func kernelEcho(_ body: KernelEchoBody) async throws -> KernelEchoPostResponse {
        let url = baseURL.appendingPathComponent("api/v1/_kernel/echo")
        let encodedBody = try JSONEncoder().encode(body)
        return try await request(url: url, method: "POST", body: encodedBody, as: KernelEchoPostResponse.self)
    }

    public func shellBootstrap() async throws -> ShellBootstrapResponse {
        let url = baseURL.appendingPathComponent("api/v1/shell/bootstrap")
        return try await request(url: url, method: "GET", body: nil, as: ShellBootstrapResponse.self)
    }

    public func appConfig() async throws -> AppConfigResponse {
        let url = baseURL.appendingPathComponent("api/v1/app-config")
        return try await request(url: url, method: "GET", body: nil, as: AppConfigResponse.self)
    }

    public func syncPull(query: SyncPullQuery = SyncPullQuery()) async throws -> SyncPullResponse {
        var components = URLComponents(url: baseURL.appendingPathComponent("api/v1/sync/pull"), resolvingAgainstBaseURL: false)
        var items: [URLQueryItem] = []
        if let cursor = query.cursor { items.append(URLQueryItem(name: "cursor", value: cursor)) }
        if let limit = query.limit { items.append(URLQueryItem(name: "limit", value: String(limit))) }
        components?.queryItems = items.isEmpty ? nil : items
        guard let url = components?.url else { throw TotemAPIError.invalidURL }
        return try await request(url: url, method: "GET", body: nil, as: SyncPullResponse.self)
    }

    public func syncPush(_ body: SyncPushBody) async throws -> SyncPushResponse {
        let encodedBody = try JSONEncoder().encode(body)
        return try await request(url: baseURL.appendingPathComponent("api/v1/sync/push"), method: "POST", body: encodedBody, as: SyncPushResponse.self)
    }

    public func syncBootstrap() async throws -> SyncBootstrapResponse {
        return try await request(url: baseURL.appendingPathComponent("api/v1/sync/bootstrap"), method: "GET", body: nil, as: SyncBootstrapResponse.self)
    }

    public func dashboard() async throws -> DashboardResponse {
        return try await request(url: baseURL.appendingPathComponent("api/v1/dashboard"), method: "GET", body: nil, as: DashboardResponse.self)
    }

    private func request<T: Decodable>(url: URL, method: String, body: Data?, as type: T.Type) async throws -> T {
        var request = URLRequest(url: url)
        request.httpMethod = method
        // Never leave native refresh controls spinning forever when the API
        // or a stale WebView cookie cannot complete the request.
        request.timeoutInterval = 15
        request.setValue("application/json", forHTTPHeaderField: "accept")
        for (name, value) in additionalHeaders {
            request.setValue(value, forHTTPHeaderField: name)
        }
        if let body {
            request.httpBody = body
            request.setValue("application/json", forHTTPHeaderField: "content-type")
            if let csrfToken { request.setValue(csrfToken, forHTTPHeaderField: "x-csrf-token") }
        }
        let (data, response) = try await session.data(for: request)
        guard let httpResponse = response as? HTTPURLResponse else {
            throw TotemAPIError.http(status: 0, problem: nil)
        }
        guard (200..<300).contains(httpResponse.statusCode) else {
            let problem = try? JSONDecoder().decode(APIProblem.self, from: data)
            throw TotemAPIError.http(status: httpResponse.statusCode, problem: problem)
        }
        do {
            return try JSONDecoder().decode(T.self, from: data)
        } catch {
            throw TotemAPIError.decoding(error)
        }
    }
}
