// AUTO-GENERATED by scripts/generate-api-contracts.mjs. Do not edit manually.
// Source: contracts/openapi.json (OpenAPI 3.1.0).

import Foundation

public enum APIProblemPathPart: Codable, Equatable {
    case key(String)
    case index(Int)

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(String.self) {
            self = .key(value)
        } else {
            self = .index(try container.decode(Int.self))
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .key(let value): try container.encode(value)
        case .index(let value): try container.encode(value)
        }
    }
}

public struct APIProblemIssue: Codable, Equatable {
    public let path: [APIProblemPathPart]
    public let code: String
    public let message: String
}

public struct APIProblem: Codable, Equatable, Error {
    public let type: String
    public let title: String
    public let status: Int
    public let detail: String
    public let instance: String
    public let code: String
    public let requestId: String
    public let retryAfter: Int?
    public let errors: [APIProblemIssue]?
}

public struct KernelItem: Codable, Equatable {
    public let id: String
    public let label: String
}

public struct KernelEchoQuery: Codable, Equatable {
    public let cursor: String?
    public let limit: Int?

    public init(cursor: String? = nil, limit: Int? = nil) {
        self.cursor = cursor
        self.limit = limit
    }
}

public struct KernelEchoBody: Codable, Equatable {
    public let message: String

    public init(message: String) {
        self.message = message
    }
}

public struct KernelEchoCursor: Codable, Equatable {
    public let version: Int
    public let offset: Int
}

public struct KernelEchoPagination: Codable, Equatable {
    public let limit: Int
    public let hasMore: Bool
    public let nextCursor: String?
}

public struct KernelEchoMeta: Codable, Equatable {
    public let requestId: String
    public let pagination: KernelEchoPagination
}

public struct KernelEchoGetResponse: Codable, Equatable {
    public let data: [KernelItem]
    public let meta: KernelEchoMeta
}

public struct KernelEchoPostData: Codable, Equatable {
    public let echo: String
}

public struct KernelEchoPostMeta: Codable, Equatable {
    public let requestId: String
}

public struct KernelEchoPostResponse: Codable, Equatable {
    public let data: KernelEchoPostData
    public let meta: KernelEchoPostMeta
}

public struct ShellBootstrapUser: Codable, Equatable {
    public let id: String
    public let name: String
    public let email: String?
    public let role: String
    public let roleLabel: String
    public let avatarUrl: String?
    public let initials: String
}

public struct ShellBootstrapPreferences: Codable, Equatable {
    public let theme: String
    public let accentColor: String
}

public struct ShellBootstrapBrand: Codable, Equatable {
    public let logoLight: String?
    public let logoDark: String?
}

public struct ShellBootstrapCounters: Codable, Equatable {
    public let pendingTasks: Int
    public let unreadNotifications: Int
}

public struct ShellBootstrapNotification: Codable, Equatable {
    public let id: String
    public let message: String
    public let createdAt: String
    public let authorName: String?
    public let avatarUrl: String?
    public let read: Bool
}

public struct ShellBootstrapData: Codable, Equatable {
    public let user: ShellBootstrapUser
    public let capabilities: [String]
    public let preferences: ShellBootstrapPreferences
    public let brand: ShellBootstrapBrand
    public let counters: ShellBootstrapCounters
    public let notifications: [ShellBootstrapNotification]
}

public struct ShellBootstrapMeta: Codable, Equatable {
    public let requestId: String
}

public struct ShellBootstrapResponse: Codable, Equatable {
    public let data: ShellBootstrapData
    public let meta: ShellBootstrapMeta
}

public enum TotemAPIError: Error {
    case invalidURL
    case http(status: Int, problem: APIProblem?)
    case decoding(Error)
}

public final class TotemAPIClient {
    private let baseURL: URL
    private let session: URLSession
    private let csrfToken: String?
    private let additionalHeaders: [String: String]

    public init(
        baseURL: URL,
        session: URLSession = .shared,
        csrfToken: String? = nil,
        additionalHeaders: [String: String] = [:]
    ) {
        self.baseURL = baseURL
        self.session = session
        self.csrfToken = csrfToken
        self.additionalHeaders = additionalHeaders
    }

    public func kernelEchoList(query: KernelEchoQuery = KernelEchoQuery()) async throws -> KernelEchoGetResponse {
        var components = URLComponents(url: baseURL.appendingPathComponent("api/v1/_kernel/echo"), resolvingAgainstBaseURL: false)
        var items: [URLQueryItem] = []
        if let cursor = query.cursor { items.append(URLQueryItem(name: "cursor", value: cursor)) }
        if let limit = query.limit { items.append(URLQueryItem(name: "limit", value: String(limit))) }
        components?.queryItems = items.isEmpty ? nil : items
        guard let url = components?.url else { throw TotemAPIError.invalidURL }
        return try await request(url: url, method: "GET", body: nil, as: KernelEchoGetResponse.self)
    }

    public func kernelEcho(_ body: KernelEchoBody) async throws -> KernelEchoPostResponse {
        let url = baseURL.appendingPathComponent("api/v1/_kernel/echo")
        let encodedBody = try JSONEncoder().encode(body)
        return try await request(url: url, method: "POST", body: encodedBody, as: KernelEchoPostResponse.self)
    }

    public func shellBootstrap() async throws -> ShellBootstrapResponse {
        let url = baseURL.appendingPathComponent("api/v1/shell/bootstrap")
        return try await request(url: url, method: "GET", body: nil, as: ShellBootstrapResponse.self)
    }

    private func request<T: Decodable>(url: URL, method: String, body: Data?, as type: T.Type) async throws -> T {
        var request = URLRequest(url: url)
        request.httpMethod = method
        request.setValue("application/json", forHTTPHeaderField: "accept")
        for (name, value) in additionalHeaders {
            request.setValue(value, forHTTPHeaderField: name)
        }
        if let body {
            request.httpBody = body
            request.setValue("application/json", forHTTPHeaderField: "content-type")
            if let csrfToken { request.setValue(csrfToken, forHTTPHeaderField: "x-csrf-token") }
        }
        let (data, response) = try await session.data(for: request)
        guard let httpResponse = response as? HTTPURLResponse else {
            throw TotemAPIError.http(status: 0, problem: nil)
        }
        guard (200..<300).contains(httpResponse.statusCode) else {
            let problem = try? JSONDecoder().decode(APIProblem.self, from: data)
            throw TotemAPIError.http(status: httpResponse.statusCode, problem: problem)
        }
        do {
            return try JSONDecoder().decode(T.self, from: data)
        } catch {
            throw TotemAPIError.decoding(error)
        }
    }
}
